
default:
  retry:
    max: 2

stages:
  - qa
  - test
  - publish
  - mirror
  - build

whitespace:
  stage: qa
  image: "dsilabs/testbase:3.7"
  script:
    - which git || (apt-get update -y && apt-get install -y git)
    - git --no-pager diff --check

python-3.7-unit:
  stage: test
  image: "dsilabs/testbase:3.7"
  script:
    - /bin/bash tests/run_unittests.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.7-web:
  stage: test
  image: "dsilabs/testbase:3.7"
  script:
    - /bin/bash tests/run_webtests_basetest.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.8-unit:
  stage: test
  image: "dsilabs/testbase:3.8"
  script:
    - /bin/bash tests/run_unittests.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.8-web:
  stage: test
  image: "dsilabs/testbase:3.8"
  script:
    - /bin/bash tests/run_webtests.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.9-unit:
  stage: test
  image: "dsilabs/testbase:3.9"
  script:
    - /bin/bash tests/run_unittests.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.9-web:
  stage: test
  image: "dsilabs/testbase:3.9"
  script:
    - /bin/bash tests/run_webtests.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.12-unit:
  stage: test
  image: "dsilabs/testbase:3.12"
  script:
    - /bin/bash tests/run_unittests.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.12-web:
  stage: test
  image: "dsilabs/testbase:3.12"
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.9-MySQL8-unit:
  stage: test
  image: "dsilabs/testbase:3.9"
  services:
    - mysql:8.4
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run_unittests_mysql.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.9-MySQL8-web:
  stage: test
  image: "dsilabs/testbase:3.9"
  services:
    - mysql:8.4
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run_webtests_mysql.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.12-MySQL8-unit:
  stage: test
  image: "dsilabs/testbase:3.12"
  services:
    - mysql:8.4
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run_unittests_mysql.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

python-3.12-MySQL8-web:
  stage: test
  image: "dsilabs/testbase:3.12"
  services:
    - mysql:8.4
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run_webtests_mysql.sh
  artifacts:
    paths:
    - tests/artifacts/
    expire_in: 1 week
    when: on_failure

pypi:
  stage: publish
  trigger: dsilabs/zoom-publisher
  only:
    - tags

mirror_to_github:
  stage: mirror
  image: alpine:latest

  before_script:

    - apk add --no-cache git openssh

    - mkdir -p ~/.ssh
    - echo "$DEPLOY_USER_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

  script:

    - git clone --bare "$CI_REPOSITORY_URL" repo
    - cd repo

    - git remote add github git@github.com:ZoomFoundry/ZoomFoundry.git
    - git push github

  only:
    - master

docker:
  stage: build
  trigger: dsilabs/docker-zoom
  only:
    - tags

docker-manual:
  stage: build
  trigger: dsilabs/docker-zoom
  when: manual
  only:
    - master
