

stages:
  - lint
  - test
  - build

whitespace:
  stage: lint
  image: "bash"
  script:
    - which git || (apt-get update -y && apt-get install -y git)
    - git --no-pager diff --check

tests:
  stage: test
  image: "python:3.7"
  services:
    - mariadb:latest
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run.sh

docker build:
  stage: build
  image: docker:stable
  script:
  - apk add --no-cache curl
  - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.dsilabs.ca/api/v4/projects/130/trigger/pipeline"
  tags:
  - shell
  only:
  - master
