

stages:
  - qa
  - test
  - build

whitespace:
  stage: qa
  image: "python:3.7"
  script:
    - which git || (apt-get update -y && apt-get install -y git)
    - git --no-pager diff --check

legacy_tests:
  stage: test
  image: "python:3.7"
  services:
    - mariadb:latest
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run_in_gitlab_ci.sh

new_tests:
  stage: test
  image: "python:3.7"
  services:
    - mariadb:latest
  variables:
    MYSQL_DATABASE: zoomtest2
    MYSQL_ROOT_PASSWORD: root
  script:
    - /bin/bash tests/run_in_gitlab_ci_new.sh

docker build:
  stage: build
  image: docker:stable
  script:
  - apk add --no-cache curl
  - "curl -X POST -F token=$TOKEN -F ref=master https://gitlab.dsilabs.ca/api/v4/projects/130/trigger/pipeline"
  only:
    - master

