language: python
sudo: false
dist: xenial

addons:
  mariadb: '10.2'
  hosts:
    - database

python:
  - '3.6'
  - '3.7'
  - '3.8'

install:
  - pip install coveralls
  - pip install nose-exclude
  - pip install -r requirements.txt

before_script:
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS zoomtest;'
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS zoomtest2;'
  - mysql -uroot zoomtest < zoom/sql/setup_mysql.sql
  - mysql -uroot < zoom/sql/create_testuser.sql
  - mysql -uroot -e 'CREATE DATABASE IF NOT EXISTS zoomdata;'
  - mysql -uroot zoomdata < zoom/sql/setup_mysql.sql
  - mysql -uroot < zoom/sql/create_zoomuser.sql
script:
  - nosetests --with-coverage --cover-package=zoom --with-doctest -v zoom tests/unittests --exclude-dir=zoom/testing --exclude-dir=zoom/cli --exclude-dir=zoom/_assets

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' && $TRAVIS_MARIADB_VERSION == '10.2' ]]; then coveralls; fi
